name = "budgetcalculator"
compatibility_date = "2024-01-01"

# Pages configuration
[pages]
# Build command for Pages
build.command = "npm run build"
# Output directory for Pages
build.output_dir = "build"
# Root directory for Pages
build.root = "."

# Environment variables
[vars]
NODE_ENV = "production"
