name = "budget-calculator"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "build"

# Environment variables
[vars]
NODE_ENV = "production"

# Analytics
[analytics_engine]
binding = "ANALYTICS"

# Optional: Add KV namespaces if you want to store budget data
# [[kv_namespaces]]
# binding = "BUDGET_DATA"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Optional: Add R2 storage if you want to store files
# [[r2_buckets]]
# binding = "BUDGET_FILES"
# bucket_name = "budget-calculator-files"
